In [1]:
import pandas as pd
import numpy as np

import gensim
from gensim.utils import simple_preprocess
import nltk
from nltk.corpus import stopwords

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

import tensorflow

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/Predicting Effective Arguments/Datasets/train.csv')
dataset.head()

discourse_id      essay_id  \
0  0013cc385424  007ACE74B050   
1  9704a709b505  007ACE74B050   
2  c22adee811b6  007ACE74B050   
3  a10d361e54e4  007ACE74B050   
4  db3e453ec4e2  007ACE74B050   

                                      discourse_text discourse_type  \
0  Hi, i'm Isaac, i'm going to be writing about h...           Lead   
1  On my perspective, I think that the face is a ...       Position   
2  I think that the face is a natural landform be...          Claim   
3  If life was on Mars, we would know by now. The...       Evidence   
4  People thought that the face was formed by ali...   Counterclaim   

  discourse_effectiveness  
0                Adequate  
1                Adequate  
2                Adequate  
3                Adequate  
4                Adequate

In [4]:
nltk.download('stopwords')
sw = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [5]:
def clean_data(sentence):
  tokens = simple_preprocess(sentence)
  tokens = [token for token in tokens if not token in sw]
  return ' '.join(tokens)
  #return tokens

In [6]:
dataset['Tokens'] = dataset['discourse_text'].apply(clean_data)
dataset.head()

discourse_id      essay_id  \
0  0013cc385424  007ACE74B050   
1  9704a709b505  007ACE74B050   
2  c22adee811b6  007ACE74B050   
3  a10d361e54e4  007ACE74B050   
4  db3e453ec4e2  007ACE74B050   

                                      discourse_text discourse_type  \
0  Hi, i'm Isaac, i'm going to be writing about h...           Lead   
1  On my perspective, I think that the face is a ...       Position   
2  I think that the face is a natural landform be...          Claim   
3  If life was on Mars, we would know by now. The...       Evidence   
4  People thought that the face was formed by ali...   Counterclaim   

  discourse_effectiveness                                             Tokens  
0                Adequate  hi isaac going writing face mars natural landf...  
1                Adequate  perspective think face natural landform dont t...  
2                Adequate  think face natural landform life mars descover...  
3                Adequate  life mars would know reason think natural land...  
4                Adequate  people thought face formed alieans thought lif...

In [7]:
dataset.drop(['discourse_id', 'essay_id'], axis=1, inplace=True)

In [8]:
dataset.head()

discourse_text discourse_type  \
0  Hi, i'm Isaac, i'm going to be writing about h...           Lead   
1  On my perspective, I think that the face is a ...       Position   
2  I think that the face is a natural landform be...          Claim   
3  If life was on Mars, we would know by now. The...       Evidence   
4  People thought that the face was formed by ali...   Counterclaim   

  discourse_effectiveness                                             Tokens  
0                Adequate  hi isaac going writing face mars natural landf...  
1                Adequate  perspective think face natural landform dont t...  
2                Adequate  think face natural landform life mars descover...  
3                Adequate  life mars would know reason think natural land...  
4                Adequate  people thought face formed alieans thought lif...

In [9]:
max_count = max(len(sentence.split(' ')) for sentence in dataset['Tokens'])
max_count

373

# Encoding

In [10]:
# import numpy as np
# from tensorflow.keras.utils import to_categorical, plot_model
# from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard
# from tensorflow.keras.preprocessing.sequence import pad_sequences

# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.layers import LSTM, Bidirectional
# from tensorflow.keras.layers import Embedding

In [11]:
# # integer encode sequences of words
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(dataset['Tokens'])
# #sequences = tokenizer.texts_to_sequences(dataset['Tokens'])

In [12]:
# def encode(sentence):
#   seq = tokenizer.texts_to_sequences([sentence])[0]
#   encoded = pad_sequences([seq], maxlen=max_count, truncating='pre')
#   return encoded[0]

In [13]:
# dataset['Encoded'] = dataset['Tokens'].apply(encode)
# dataset.head()

In [14]:
ohe = OneHotEncoder()

In [15]:
discourse_type_ohe = pd.DataFrame(ohe.fit_transform(dataset[['discourse_type']]).toarray())
discourse_type_ohe.head()

0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [16]:
dataset = pd.concat([dataset['Tokens'], discourse_type_ohe, dataset['discourse_effectiveness']], axis=1)
dataset.head()

Tokens    0    1    2    3    4  \
0  hi isaac going writing face mars natural landf...  0.0  0.0  0.0  0.0  1.0   
1  perspective think face natural landform dont t...  0.0  0.0  0.0  0.0  0.0   
2  think face natural landform life mars descover...  1.0  0.0  0.0  0.0  0.0   
3  life mars would know reason think natural land...  0.0  0.0  0.0  1.0  0.0   
4  people thought face formed alieans thought lif...  0.0  0.0  1.0  0.0  0.0   

     5    6 discourse_effectiveness  
0  0.0  0.0                Adequate  
1  1.0  0.0                Adequate  
2  0.0  0.0                Adequate  
3  0.0  0.0                Adequate  
4  0.0  0.0                Adequate

# LSTM

In [17]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard
import tensorflow

In [18]:
dataset.head()

Tokens    0    1    2    3    4  \
0  hi isaac going writing face mars natural landf...  0.0  0.0  0.0  0.0  1.0   
1  perspective think face natural landform dont t...  0.0  0.0  0.0  0.0  0.0   
2  think face natural landform life mars descover...  1.0  0.0  0.0  0.0  0.0   
3  life mars would know reason think natural land...  0.0  0.0  0.0  1.0  0.0   
4  people thought face formed alieans thought lif...  0.0  0.0  1.0  0.0  0.0   

     5    6 discourse_effectiveness  
0  0.0  0.0                Adequate  
1  1.0  0.0                Adequate  
2  0.0  0.0                Adequate  
3  0.0  0.0                Adequate  
4  0.0  0.0                Adequate

In [19]:
voc_size = 16000
embedding_vector_features = 500

In [20]:
# One hot representation of words
onehot_repr=[one_hot(sentence,voc_size) for sentence in dataset['Tokens']] 
#onehot_repr

In [21]:
onehot_repr

[[4901,
  9546,
  10923,
  14828,
  5306,
  4722,
  5472,
  6888,
  13603,
  4722,
  4032,
  5357,
  986,
  15684,
  1348,
  4722,
  5306,
  13918,
  11527,
  986,
  3034,
  6888,
  9260,
  13603,
  4722,
  5472,
  6888],
 [15312,
  7294,
  5306,
  5472,
  6888,
  745,
  7294,
  13603,
  4722,
  15214,
  3566,
  6246,
  7294,
  5472,
  6888],
 [7294, 5306, 5472, 6888, 13603, 4722, 15708, 15079],
 [13603,
  4722,
  13295,
  3034,
  11517,
  7294,
  5472,
  6888,
  13105,
  1968,
  4722,
  5126,
  8750,
  14030,
  11978,
  11121,
  7969,
  12255,
  14027,
  14165,
  7969,
  3034,
  5472,
  6888,
  14577,
  14165,
  12567,
  5472,
  6888],
 [2813, 13675, 5306, 5925, 14336, 13675, 13603, 4722],
 [2599, 1813, 13603, 4722, 184, 7294, 13603, 4722],
 [11978,
  11121,
  9222,
  4722,
  12792,
  9705,
  8041,
  14027,
  12017,
  4832,
  8304,
  14802,
  15684,
  1348,
  4722,
  6805,
  15442,
  5306,
  5472,
  6888],
 [6608,
  13675,
  4032,
  14336,
  15619,
  2599,
  6287,
  7294,
  6287,
  13

In [22]:
one_hot_dict = dict()

In [23]:
for encodingList, tokensList in zip(onehot_repr, dataset['Tokens']):
  tokensList = tokensList.split(' ')
  for index, word in zip(encodingList, tokensList):
    one_hot_dict[word] = index

In [24]:
# Embedding the sentences
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=max_count)
print(embedded_docs)

[[    0     0     0 ...  4722  5472  6888]
 [    0     0     0 ...  7294  5472  6888]
 [    0     0     0 ...  4722 15708 15079]
 ...
 [    0     0     0 ...  6209 13458  1813]
 [    0     0     0 ...  1227 12029 11985]
 [    0     0     0 ...  2332 10535 13137]]


In [25]:
discourse_type_ohe = np.array(discourse_type_ohe)
discourse_type_ohe

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [26]:
embedded_docs.shape

(36765, 373)

In [27]:
embedded_docs = np.hstack((embedded_docs, discourse_type_ohe))
embedded_docs

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
embedded_docs.shape

(36765, 380)

In [29]:
sum(pd.DataFrame(embedded_docs).isnull().sum())

0

In [30]:
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=embedded_docs.shape[1]))
model.add(Dropout(0.3))

model.add(LSTM(512, activation='relu', return_sequences=True))
model.add(Dropout(0.3))

model.add(LSTM(256, activation='relu', return_sequences=True))
model.add(Dropout(0.3))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(128,activation='relu'))
model.add(Dense(3,activation='softmax'))
optimizer = tensorflow.keras.optimizers.Adadelta(learning_rate=.01)
model.compile(loss= 'categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [31]:
my_callbacks_lstm = [
    EarlyStopping(patience=2),
    ModelCheckpoint(filepath='/content/drive/MyDrive/Predicting Effective Arguments/LSTM_WordEmbeddings/Callbacks/model.{epoch:02d}-{val_loss:.2f}.h5'),
    TensorBoard(log_dir='/content/drive/MyDrive/Predicting Effective Arguments/LSTM_WordEmbeddings/logs'),
]

In [32]:
le = LabelEncoder()
dataset['le_discourse_effectiveness'] = le.fit_transform(dataset['discourse_effectiveness'])
dataset.head()

Tokens    0    1    2    3    4  \
0  hi isaac going writing face mars natural landf...  0.0  0.0  0.0  0.0  1.0   
1  perspective think face natural landform dont t...  0.0  0.0  0.0  0.0  0.0   
2  think face natural landform life mars descover...  1.0  0.0  0.0  0.0  0.0   
3  life mars would know reason think natural land...  0.0  0.0  0.0  1.0  0.0   
4  people thought face formed alieans thought lif...  0.0  0.0  1.0  0.0  0.0   

     5    6 discourse_effectiveness  le_discourse_effectiveness  
0  0.0  0.0                Adequate                           0  
1  1.0  0.0                Adequate                           0  
2  0.0  0.0                Adequate                           0  
3  0.0  0.0                Adequate                           0  
4  0.0  0.0                Adequate                           0

In [33]:
ohe_discourse_effectiveness = pd.get_dummies(dataset['discourse_effectiveness'])
ohe_discourse_effectiveness

Adequate  Effective  Ineffective
0             1          0            0
1             1          0            0
2             1          0            0
3             1          0            0
4             1          0            0
...         ...        ...          ...
36760         1          0            0
36761         1          0            0
36762         1          0            0
36763         0          0            1
36764         0          0            1

[36765 rows x 3 columns]

In [34]:
X_LSTM = embedded_docs.copy()
y_LSTM = ohe_discourse_effectiveness.copy()
#y_LSTM = dataset['le_discourse_effectiveness']

In [35]:
X_LSTM.shape, y_LSTM.shape

((36765, 380), (36765, 3))

In [36]:
X_train_lstm, X_test_lstm, y_train_lstm, y_test_lstm = train_test_split(X_LSTM, y_LSTM, test_size=.33, random_state=42, shuffle=True)

In [37]:
#model.fit(X_train_lstm, y_train_lstm, validation_data=(X_test_lstm, y_test_lstm), epochs=10, batch_size=512, callbacks=my_callbacks_lstm)

In [38]:
# Saving the model
#tensorflow.keras.models.save_model(model, '/content/drive/MyDrive/Predicting Effective Arguments/Models/model.h5')

# Check model's performance

In [39]:
test = pd.read_csv('/content/drive/MyDrive/Predicting Effective Arguments/Datasets/test.csv')
test.head()

discourse_id      essay_id  \
0  a261b6e14276  D72CB1C11673   
1  5a88900e7dc1  D72CB1C11673   
2  9790d835736b  D72CB1C11673   
3  75ce6d68b67b  D72CB1C11673   
4  93578d946723  D72CB1C11673   

                                      discourse_text discourse_type  
0  Making choices in life can be very difficult. ...           Lead  
1  Seeking multiple opinions can help a person ma...       Position  
2                     it can decrease stress levels           Claim  
3             a great chance to learn something new           Claim  
4               can be very helpful and beneficial.           Claim

In [40]:
test['Tokens'] = test['discourse_text'].apply(clean_data)
test.head()

discourse_id      essay_id  \
0  a261b6e14276  D72CB1C11673   
1  5a88900e7dc1  D72CB1C11673   
2  9790d835736b  D72CB1C11673   
3  75ce6d68b67b  D72CB1C11673   
4  93578d946723  D72CB1C11673   

                                      discourse_text discourse_type  \
0  Making choices in life can be very difficult. ...           Lead   
1  Seeking multiple opinions can help a person ma...       Position   
2                     it can decrease stress levels           Claim   
3             a great chance to learn something new           Claim   
4               can be very helpful and beneficial.           Claim   

                                              Tokens  
0  making choices life difficult people often ask...  
1  seeking multiple opinions help person make bet...  
2                             decrease stress levels  
3                   great chance learn something new  
4                                 helpful beneficial

In [41]:
discourse_id = test['discourse_id']

In [42]:
test.drop(['discourse_id', 'essay_id'], axis=1, inplace=True)

In [43]:
discourse_type_ohe_test = pd.DataFrame(ohe.transform(test[['discourse_type']]).toarray())
discourse_type_ohe_test.head()

0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [44]:
def encode_test_tokens(sentence):
  encoded_tokens = [one_hot_dict[token] for token in sentence.split(' ')]
  return encoded_tokens

In [45]:
# One hot representation of words
one_hot_repr_test = [encode_test_tokens(sentence) for sentence in test['Tokens']]
#one_hot_repr_test


# Embedding the sentences
embedded_docs_test = pad_sequences(one_hot_repr_test, padding='pre', maxlen=max_count)
#print(embedded_docs_test)

discourse_type_ohe_test = np.array(discourse_type_ohe_test)
#discourse_type_ohe

embedded_docs_test = np.hstack((embedded_docs_test, discourse_type_ohe_test))
embedded_docs_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
sum(pd.DataFrame(embedded_docs_test).isnull().sum())

0

In [47]:
# test = pd.concat([test['Tokens'], discourse_type_ohe_test], axis=1)
# test.head()

In [48]:
# Loading the model
model = tensorflow.keras.models.load_model('/content/drive/MyDrive/Predicting Effective Arguments/Models/model.h5')

In [49]:
embedded_docs.shape, embedded_docs_test.shape

((36765, 380), (10, 380))

In [50]:
predictions = model.predict(embedded_docs_test)

In [51]:
predictions = pd.DataFrame(predictions, columns=['Ineffective', 'Adequate', 'Effective'])

In [52]:
predictions = pd.concat([discourse_id, predictions], axis=1)
predictions

discourse_id  Ineffective  Adequate  Effective
0  a261b6e14276     0.447642  0.308937   0.243421
1  5a88900e7dc1     0.451453  0.307884   0.240662
2  9790d835736b     0.454084  0.307157   0.238759
3  75ce6d68b67b     0.452851  0.307498   0.239651
4  93578d946723     0.455656  0.306748   0.237596
5  2e214524dbe3     0.446567  0.308967   0.244467
6  84812fc2ab9f     0.447475  0.308920   0.243605
7  c668ff840720     0.452882  0.307369   0.239749
8  739a6d00f44a     0.447384  0.308455   0.244161
9  bcfae2c9a244     0.447319  0.308890   0.243790

In [53]:
predictions.to_csv('/content/drive/MyDrive/Predicting Effective Arguments/Datasets/Predictions.csv', index=False)

In [54]:
submission = predictions.copy()

In [56]:
submission

discourse_id  Ineffective  Adequate  Effective
0  a261b6e14276     0.447642  0.308937   0.243421
1  5a88900e7dc1     0.451453  0.307884   0.240662
2  9790d835736b     0.454084  0.307157   0.238759
3  75ce6d68b67b     0.452851  0.307498   0.239651
4  93578d946723     0.455656  0.306748   0.237596
5  2e214524dbe3     0.446567  0.308967   0.244467
6  84812fc2ab9f     0.447475  0.308920   0.243605
7  c668ff840720     0.452882  0.307369   0.239749
8  739a6d00f44a     0.447384  0.308455   0.244161
9  bcfae2c9a244     0.447319  0.308890   0.243790

In [55]:
submission.to_csv('submission.csv', index=False)